Task 3 list
LeonardoReMake/android_1c pull request #2
Opened 2019-11-25 23:31 UTC by LeonardoReMake

2019-11-27 20:30 UTC, IvanShafran requested changes

2019-11-27 20:30 UTC, IvanShafran commented on app/build.gradle
> +    compileSdkVersion 28
Можно и 29 уже

2019-11-27 20:30 UTC, IvanShafran commented on app/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?><manifest package="ru.smirnov.test.a1c_course_app"          xmlns:android="http://schemas.android.com/apk/res/android">    <application        android:allow
Странные символы ^M
Это что?)

2019-11-27 20:30 UTC, IvanShafran commented on app/src/main/java/ru/smirnov/test/a1c_course_app/ui/SecondActivity.java
> +public class SecondActivity extends AppCompatActivity {
Название не годится(
На этом экране отображается подробный вид заметки.
Обычно такое называют NoteDetailActivity. Можешь выбрать любое другое название, но не second :)

2019-11-27 20:30 UTC, IvanShafran commented on app/src/main/res/layout/activity_detail.xml
> +        android:layout_width="match_parent"
Внутри ConstraintLayout не рекомендуется использовать match_parent. 
Следует ставить 0dp и constrains выставить.

2019-11-27 20:30 UTC, IvanShafran commented on app/src/main/res/layout/activity_detail.xml
> +        android:maxWidth="250dp"
Я подразумевал, что картинка и текст делят экран пополам.
max размеры её указывать не надо. Достаточно добавить margin 16dp от краев

2019-11-27 20:30 UTC, IvanShafran commented on app/src/main/res/layout/note_item.xml
> +    android:layout_height="wrap_content"
Высоту стоит выставить фиксированную, чтобы не тратилось время на вычисления размера при показе списка

2019-11-27 20:30 UTC, IvanShafran commented on app/src/main/res/layout/note_item.xml
> +            android:layout_width="wrap_content"
Тут имелось в виду фиксированные размеры 96 на 96 dp, чтобы все элементы списка однообразно выглядели

2019-12-12 17:40 UTC, LeonardoReMake commented on app/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?><manifest package="ru.smirnov.test.a1c_course_app"          xmlns:android="http://schemas.android.com/apk/res/android">    <application        android:allow
Возможно из-за Line Separator :) Поменял в новой версии, должно исчезнуть

> Странные символы ^M
> Это что?)

2019-12-12 18:05 UTC, IvanShafran approved these changes

2019-12-12 18:05 UTC, merged